local Cached = {
  Seeds = {"Carrot","Strawberry","Blueberry","Tomato","Cauliflower","Watermelon","Green Apple","Avocado","Banana","Pineapple","Kiwi","Bell Pepper","Prickly Pear","Loquat","Feijoa"},
  Gears = { "Watering Can", "Trowel", "Recall Wrench", "Basic Sprinkler", "Advanced Sprinkler", "Godly Sprinkler", "Lightning Rod", "Master Sprinkler", "Favorite Tool", "Harvest Tool", "Friendship Pot" },
  Pets = { "Kiwi", "Blood Kiwi", "Owl", "Panda", "Spotted Deer", "Golden Lab", "Frog", "Pack Bee", "Cooked Owl", "Red Dragon", "Cow", "Bunny", "Praying Mantis", "Queen Bee", "Caterpillar", "Golden Bee", "Turtle", "Dog", "Butterfly", "Disco Bee", "Firefly", "Moth", "Deer", "Red Giant Ant", "Tarantula Hawk", "Wasp", "Night Owl", "Bear Bee", "Monkey", "Honey Bee", "Squirrel", "Petal Bee", "Bee", "Moon Cat", "Cat", "Blood Owl", "Black Bunny", "Brown Mouse", "Blood Hedgehog", "Silver Monkey", "Chicken", "Chicken Zombie", "Red Fox", "Orange Tabby", "Echo Frog", "Grey Mouse", "Dragonfly", "Mole", "Raccoon", "Hedgehog", "Sea Otter", "Rooster", "Giant Ant", "Polar Bear", "Pig", "Snail" },
  Honeys = { "Flower Seed Pack", "Lavender", "Nectarshade", "Nectarine", "Hive Fruit", "Pollen Radar", "Nectar Staff", "Honey Sprinkler", "Bee Egg", "Bee Crate", "Honey Comb", "Bee Chair", "Honey Torch", "Honey Walkway" },
  Attributes = {"Pollinated", "Wet", "Frozen", "Rainbow", "Celesial", "Moonlit"},
  Weather = {"BeeSwarm","FrostEvent","KillerBunny","MeteorShower","NightEvent","RainEvent","ThunderStorm"},
  NPCs = {["Sell NPC"] = CFrame.new(92, 4, 2)}
}
return Cached
